///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AdvExamples
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AdvExamplesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1bcdd418-4008-400d-b742-81d88fba5d04")]
    public partial class AdvExamplesRepository : RepoGenBaseFolder
    {
        static AdvExamplesRepository instance = new AdvExamplesRepository();
        AdvExamplesRepositoryFolders.MainFormAppFolder _mainform;
        AdvExamplesRepositoryFolders.KeePassAppFolder _keepass;
        AdvExamplesRepositoryFolders.OptionsFormAppFolder _optionsform;

        /// <summary>
        /// Gets the singleton class instance representing the AdvExamplesRepository element repository.
        /// </summary>
        [RepositoryFolder("1bcdd418-4008-400d-b742-81d88fba5d04")]
        public static AdvExamplesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AdvExamplesRepository() 
            : base("AdvExamplesRepository", "/", null, 0, false, "1bcdd418-4008-400d-b742-81d88fba5d04", ".\\RepositoryImages\\AdvExamplesRepository1bcdd418.rximgres")
        {
            _mainform = new AdvExamplesRepositoryFolders.MainFormAppFolder(this);
            _keepass = new AdvExamplesRepositoryFolders.KeePassAppFolder(this);
            _optionsform = new AdvExamplesRepositoryFolders.OptionsFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1bcdd418-4008-400d-b742-81d88fba5d04")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("eccf2f4c-fdc8-4acc-8c6b-d4cc8522331b")]
        public virtual AdvExamplesRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("a31398f7-708c-47c3-90e6-ee06c7278f8c")]
        public virtual AdvExamplesRepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }

        /// <summary>
        /// The OptionsForm folder.
        /// </summary>
        [RepositoryFolder("cd602bee-21fd-43d5-bc32-9b9f4356ded9")]
        public virtual AdvExamplesRepositoryFolders.OptionsFormAppFolder OptionsForm
        {
            get { return _optionsform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AdvExamplesRepositoryFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("eccf2f4c-fdc8-4acc-8c6b-d4cc8522331b")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _toolsInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "eccf2f4c-fdc8-4acc-8c6b-d4cc8522331b", "")
            {
                _toolsInfo = new RepoItemInfo(this, "Tools", "?/?/menuitem[@accessiblename='Tools']", "", 30000, null, "7456f049-1265-4a47-97b4-0d5fcc9c1cfb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eccf2f4c-fdc8-4acc-8c6b-d4cc8522331b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eccf2f4c-fdc8-4acc-8c6b-d4cc8522331b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tools item.
            /// </summary>
            [RepositoryItem("7456f049-1265-4a47-97b4-0d5fcc9c1cfb")]
            public virtual Ranorex.MenuItem Tools
            {
                get
                {
                    return _toolsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Tools item info.
            /// </summary>
            [RepositoryItemInfo("7456f049-1265-4a47-97b4-0d5fcc9c1cfb")]
            public virtual RepoItemInfo ToolsInfo
            {
                get
                {
                    return _toolsInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("a31398f7-708c-47c3-90e6-ee06c7278f8c")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _optionsInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/contextmenu[@processname='KeePass']", parentFolder, 30000, null, true, "a31398f7-708c-47c3-90e6-ee06c7278f8c", "")
            {
                _optionsInfo = new RepoItemInfo(this, "Options", "menuitem[@accessiblename='Options...']", "", 30000, null, "86244de8-72c2-46be-9117-d60c557f6893");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a31398f7-708c-47c3-90e6-ee06c7278f8c")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a31398f7-708c-47c3-90e6-ee06c7278f8c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Options item.
            /// </summary>
            [RepositoryItem("86244de8-72c2-46be-9117-d60c557f6893")]
            public virtual Ranorex.MenuItem Options
            {
                get
                {
                    return _optionsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Options item info.
            /// </summary>
            [RepositoryItemInfo("86244de8-72c2-46be-9117-d60c557f6893")]
            public virtual RepoItemInfo OptionsInfo
            {
                get
                {
                    return _optionsInfo;
                }
            }
        }

        /// <summary>
        /// The OptionsFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("cd602bee-21fd-43d5-bc32-9b9f4356ded9")]
        public partial class OptionsFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _interfaceInfo;

            /// <summary>
            /// Creates a new OptionsForm  folder.
            /// </summary>
            public OptionsFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OptionsForm", "/form[@controlname='OptionsForm']", parentFolder, 30000, null, true, "cd602bee-21fd-43d5-bc32-9b9f4356ded9", "")
            {
                _interfaceInfo = new RepoItemInfo(this, "Interface", "?/?/tabpage[@accessiblename='Interface']", "", 30000, null, "5bce03ca-af1f-4017-9fe9-279b98310c9a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd602bee-21fd-43d5-bc32-9b9f4356ded9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd602bee-21fd-43d5-bc32-9b9f4356ded9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Interface item.
            /// </summary>
            [RepositoryItem("5bce03ca-af1f-4017-9fe9-279b98310c9a")]
            public virtual Ranorex.TabPage Interface
            {
                get
                {
                    return _interfaceInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Interface item info.
            /// </summary>
            [RepositoryItemInfo("5bce03ca-af1f-4017-9fe9-279b98310c9a")]
            public virtual RepoItemInfo InterfaceInfo
            {
                get
                {
                    return _interfaceInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
