///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AdvExamples
{
    public partial class WebTable
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CountRowsWithFind()
        {
            TableTag myTable = "/dom[@domain>'edgewordstraining.co.uk']//div[#'formResults']/table";
            
            
            
            int numRows = myTable.Find(".//tr").Count; // Note ".//tr" *not* "//tr" - which would start the search from root, instead of inside table
            
//            //Find returns a collection so the above is equivalent to:
//            IList<Ranorex.Adapter> myCollection = myTable.Find(".//tr");
//            int numRows = myCollection.Count;
            
            Report.Info("Num rows = " + numRows);
        }

        public void ShowFindSingle()
        {
            // .Find<T>()
            
            TableTag myTable = "/dom[@domain>'edgewordstraining.co.uk']//div[#'formResults']/table";
            
//            var FirstMatch = myTable.FindSingle(".//tr"); //Returns 1st match as generic element
//            
//            FirstMatch.As<Ranorex.WebElement>().Click();
            
            var FirstMatch = myTable.FindSingle<Ranorex.WebElement>(".//tr"); //Returns 1st match as specified type
            
            FirstMatch.Click();
            
            
            
        }


    }
}
